### ISSUE TITLE
Can you add expansion screws?

### ISSUE THREAD

**Issue by Yo-Snowpro** [ThePhaseCat/GalvanizedVeneers#1]
Make galvanized square steel a gravity block and have the expansion screws make it float if you right click with them.

**Comment by ThePhaseCat** [comment]
oh wait that's actually perfect, if I have some spare time I'll add it

**Comment by Yo-Snowpro** [comment]
Sounds good

**Comment by ThePhaseCat** [comment]
added with v1.2.0

ty again for the suggestion!
